"""create todos table

Revision ID: 464ec6b66615
Revises: f325f0a8fd5b
Create Date: 2026-07-08 17:21:14.176450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464ec6b66615'
down_revision: Union[str, Sequence[str], None] = 'f325f0a8fd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('fixed_time', sa.Integer(), nullable=True),
    sa.Column('scheduled_time', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Float(), server_default='0', nullable=False),
    sa.Column('weekly_goal_id', sa.Uuid(), nullable=True),
    sa.Column('is_done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_scheduled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['weekly_goal_id'], ['weekly_goals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
