"""add note reason source to todos

Revision ID: 4c43438ab9ee
Revises: 464ec6b66615
Create Date: 2026-07-08 18:41:50.062355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c43438ab9ee'
down_revision: Union[str, Sequence[str], None] = '464ec6b66615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('note', sa.String(), nullable=True))
    op.add_column('todos', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('todos', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'source')
    op.drop_column('todos', 'reason')
    op.drop_column('todos', 'note')
    # ### end Alembic commands ###
