"""normalize schedules into own table

Revision ID: 9df96523fed2
Revises: 4c43438ab9ee
Create Date: 2026-07-08 22:55:17.051310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df96523fed2'
down_revision: Union[str, Sequence[str], None] = '4c43438ab9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('todo_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_time', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('todo_id')
    )
    op.drop_column('todos', 'reason')
    op.drop_column('todos', 'source')
    op.drop_column('todos', 'note')
    op.drop_column('todos', 'is_scheduled')
    op.drop_column('todos', 'scheduled_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('scheduled_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('todos', sa.Column('is_scheduled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('todos', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('todos', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('todos', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('schedules')
    # ### end Alembic commands ###
